version: "3.8"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: frauddb
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
